# Generated by Django 3.2.11 on 2022-02-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
